version: "3"
services:
  helloworld:
    image: kornkitti/express-hello-world
    networks:
      internal:
        aliases:
        - helloworld
  tunnel:
    build: ../
    tty: true
    stdin_open: true
    restart: always
    env_file:
    - tunnel.env
    depends_on:
    - helloworld
    environment:
    - KEY_NAME=key_rsa
    volumes:
    - ~/.ssh/key_rsa:/root/.ssh/key_rsa
    networks:
      internal:

networks:
  internal:
